const { Schema, model, models } = require("mongoose");

//database model for database
const MovieSchema = new Schema(
  {
    title: { type: String },
    slug: { type: String, required: true },
    bgposter: { type: String },
    smposter: { type: String },
    titlecategory: { type: String },
    description: { type: String },
    rating: { type: String },
    duration: { type: String },
    episodes: { type: String },
    year: { type: String },
    type: { type: String },
    genre: [{ type: String }],
    language: { type: String },
    subtitle: { type: String },
    size: { type: String },
    quality: { type: String },
    youtubelink: { type: String },
    streamlink: { type: String },
    category: { type: String },
    watchonline: { type: String },
    downloadlink: {
      "480p": { type: String },
      "720p": { type: String },
      "1080p": { type: String },
      "4k": { type: String },
      "480p2": { type: String },
      "720p2": { type: String },
      "1080p2": { type: String },
      "t480p": { type: String },
      "t720p": { type: String },
      "t1080p": { type: String },
    
      "t480p2": { type: String },
      "t720p2": { type: String },
      "t1080p2": { type: String },
      "4k": { type: String },
      "ep1": { type: String },
      "ep2": { type: String },
      "ep3": { type: String },
      "ep4": { type: String },
      "ep5": { type: String },
      "ep6": { type: String },
      "ep7": { type: String },
      "ep8": { type: String },
      "ep9": { type: String },
      "ep10": { type: String },
      "ep11": { type: String },
      "ep12": { type: String },
      "ep13": { type: String },
      "ep14": { type: String },
      "ep15": { type: String },
      "ep16": { type: String },
      "ep17": { type: String },
      "ep18": { type: String },
      "ep19": { type: String },
      "ep20": { type: String },
      "ep21": { type: String },
      "ep22": { type: String },
      "ep23": { type: String },
      "ep24": { type: String },
      "ep25": { type: String },
      "ep26": { type: String },
      "ep27": { type: String },
      "ep28": { type: String },
      "ep29": { type: String },
      "ep30": { type: String },
    },
    status: { type: String },
  },
  {
    timestamps: true, //this option will auto manage createAt and UpdateAt fields
  }
);

export const Movie = models.Movie || model('Movie', MovieSchema, 'movies');
